import { useState } from 'react';

type Priority = 'MUST HAVE' | 'HIGH' | 'NICE TO HAVE';
type PhotoType = 'REAL PHOTO' | 'STOCK OK';

interface ImageItem {
  id: string;
  page: string;
  section: string;
  description: string;
  dimensions: string;
  aspectRatio: string;
  priority: Priority;
  photoType: PhotoType;
  canLaunchWithout: boolean;
  filename: string;
}

const images: ImageItem[] = [
  // ─── HERO ───────────────────────────────────────────────────────────────────
  {
    id: 'hero-bg',
    page: 'Home',
    section: 'Hero Background',
    description: 'Full-viewport overhead or 45° shot of the Combo Over Rice platter — chicken AND lamb sliced on top of saffron rice, both white garlic sauce AND red spicy sauce drizzled dramatically, steam visible, shot on dark surface',
    dimensions: '1920×1080px minimum',
    aspectRatio: '16:9',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'hero-combo-platter-bg.jpg',
  },
  {
    id: 'hero-card',
    page: 'Home',
    section: 'Hero Right Card',
    description: 'Close-up overhead of the Combo Over Rice platter (same dish), tighter crop, crisp focus on the meat + rice + sauce drizzle. Shot on dark plate or tray.',
    dimensions: '700×500px',
    aspectRatio: '7:5',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'hero-combo-platter-card.jpg',
  },

  // ─── BEST SELLERS ────────────────────────────────────────────────────────────
  {
    id: 'bs-combo',
    page: 'Home',
    section: 'Best Sellers Grid',
    description: 'Combo Over Rice — overhead or slight angle, chicken + lamb slices on saffron rice, both sauces drizzled, side salad visible, generous portion',
    dimensions: '600×450px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'best-seller-combo-over-rice.jpg',
  },
  {
    id: 'bs-lamb-rice',
    page: 'Home',
    section: 'Best Sellers Grid',
    description: 'Lamb Over Rice — tender halal lamb slices on saffron rice, red + white sauce drizzle, side salad, plated on styrofoam or real plate',
    dimensions: '600×450px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'best-seller-lamb-over-rice.jpg',
  },
  {
    id: 'bs-chicken-shawarma-wrap',
    page: 'Home',
    section: 'Best Sellers Grid',
    description: 'Chicken Shawarma Wrap — pita wrap cut in half showing the filling: chicken, veggies, garlic sauce oozing out. Shot on parchment paper or board.',
    dimensions: '600×450px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'best-seller-chicken-shawarma-wrap.jpg',
  },
  {
    id: 'bs-mixed-grill',
    page: 'Home',
    section: 'Best Sellers Grid',
    description: 'Mixed Grill feast — lamb chops + chicken skewer + kafta skewer on a large plate or over rice. Char marks visible. Shot on dark surface with dramatic lighting.',
    dimensions: '600×450px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'best-seller-mixed-grill.jpg',
  },
  {
    id: 'bs-lamb-gyro',
    page: 'Home',
    section: 'Best Sellers Grid',
    description: 'Lamb Gyro Wrap — wrapped pita or flatbread, lamb slices visible, tzatziki or white sauce drizzle, tomatoes, lettuce peeking out. Cut in half.',
    dimensions: '600×450px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'best-seller-lamb-gyro-wrap.jpg',
  },
  {
    id: 'bs-falafel-rice',
    page: 'Home',
    section: 'Best Sellers Grid',
    description: 'Falafel Over Rice — golden-brown crispy falafel balls over saffron rice, tahini drizzled, side salad. Vibrant, colorful.',
    dimensions: '600×450px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'best-seller-falafel-over-rice.jpg',
  },

  // ─── SAUCE SECTION ───────────────────────────────────────────────────────────
  {
    id: 'sauce-drizzle',
    page: 'Home',
    section: 'Sauce Callout',
    description: 'Action shot: white garlic sauce AND red spicy sauce being drizzled simultaneously (or two separate close-ups stitched) over a lamb/chicken rice platter. Sauce motion blur is ideal. Dark background, warm lighting.',
    dimensions: '700×420px',
    aspectRatio: '5:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'sauce-drizzle-action.jpg',
  },

  // ─── FAMILY STORY / ABOUT PREVIEW ───────────────────────────────────────────
  {
    id: 'ibrahim-grill',
    page: 'Home + About',
    section: 'Family Story Section',
    description: 'Ibrahim at the grill — candid, not staged. Could be: flipping chicken, slicing lamb off spit, plating a dish, or smiling at camera in the kitchen. Warm lighting, authentic feel. NOT a posed stock photo.',
    dimensions: '700×480px',
    aspectRatio: '3:2',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'ibrahim-owner-grill.jpg',
  },

  // ─── GALLERY STRIP (12 PHOTOS) ───────────────────────────────────────────────
  {
    id: 'gal-1',
    page: 'Home',
    section: 'Gallery Strip',
    description: 'Overhead shot of Combo Over Rice platter — hero plate, wide shot, lots of food',
    dimensions: '600×400px',
    aspectRatio: '3:2',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'gallery-01-combo-overhead.jpg',
  },
  {
    id: 'gal-2',
    page: 'Home',
    section: 'Gallery Strip',
    description: 'Lamb chops on the grill — raw or mid-cook, char marks, flame or glow visible',
    dimensions: '600×400px',
    aspectRatio: '3:2',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'gallery-02-lamb-chops-grill.jpg',
  },
  {
    id: 'gal-3',
    page: 'Home',
    section: 'Gallery Strip',
    description: 'Chicken skewers being grilled — action shot, maybe slight fire, golden char visible',
    dimensions: '600×400px',
    aspectRatio: '3:2',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'gallery-03-chicken-skewers-grill.jpg',
  },
  {
    id: 'gal-4',
    page: 'Home',
    section: 'Gallery Strip',
    description: 'White garlic sauce close-up in a small container or being drizzled — creamy, glossy',
    dimensions: '600×400px',
    aspectRatio: '3:2',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'gallery-04-white-sauce-closeup.jpg',
  },
  {
    id: 'gal-5',
    page: 'Home',
    section: 'Gallery Strip',
    description: 'Mixed Grill platter laid out — all proteins on one plate, vibrant and impressive',
    dimensions: '600×400px',
    aspectRatio: '3:2',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'gallery-05-mixed-grill-platter.jpg',
  },
  {
    id: 'gal-6',
    page: 'Home',
    section: 'Gallery Strip',
    description: 'Restaurant interior — counter, signage, seating area. Clean, inviting, real feel.',
    dimensions: '600×400px',
    aspectRatio: '3:2',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'gallery-06-interior.jpg',
  },
  {
    id: 'gal-7',
    page: 'Home',
    section: 'Gallery Strip',
    description: 'Outdoor seating or storefront exterior — daytime, clean signage visible',
    dimensions: '600×400px',
    aspectRatio: '3:2',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'gallery-07-exterior-storefront.jpg',
  },
  {
    id: 'gal-8',
    page: 'Home',
    section: 'Gallery Strip',
    description: 'Team behind the counter — Ibrahim + staff smiling, busy service moment or posed group photo',
    dimensions: '600×400px',
    aspectRatio: '3:2',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'gallery-08-team-counter.jpg',
  },
  {
    id: 'gal-9',
    page: 'Home',
    section: 'Gallery Strip',
    description: 'Falafel close-up — fresh out of fryer, golden brown, cracked open showing green inside',
    dimensions: '600×400px',
    aspectRatio: '3:2',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'gallery-09-falafel-closeup.jpg',
  },
  {
    id: 'gal-10',
    page: 'Home',
    section: 'Gallery Strip',
    description: 'Hot black tea in a glass cup — dine-in setting, mint leaf, warm lighting. Iconic complimentary item.',
    dimensions: '600×400px',
    aspectRatio: '3:2',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'gallery-10-hot-black-tea.jpg',
  },
  {
    id: 'gal-11',
    page: 'Home',
    section: 'Gallery Strip',
    description: 'Chicken shawarma being sliced off the rotisserie spit — action, motion, steam',
    dimensions: '600×400px',
    aspectRatio: '3:2',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'gallery-11-shawarma-spit-slice.jpg',
  },
  {
    id: 'gal-12',
    page: 'Home',
    section: 'Gallery Strip',
    description: 'Baklava or dessert close-up — honey glistening, pistachio crumbles, warm plating',
    dimensions: '600×400px',
    aspectRatio: '3:2',
    priority: 'NICE TO HAVE',
    photoType: 'STOCK OK',
    canLaunchWithout: true,
    filename: 'gallery-12-baklava-dessert.jpg',
  },

  // ─── CATERING PAGE ───────────────────────────────────────────────────────────
  {
    id: 'catering-hero',
    page: 'Catering',
    section: 'Hero',
    description: 'Large catering spread — multiple trays/containers of food set up buffet-style for a party or event. Rice, chicken, lamb, salads all visible. Could be a real event they catered.',
    dimensions: '1400×600px',
    aspectRatio: '21:9',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'catering-hero-spread.jpg',
  },
  {
    id: 'catering-setup',
    page: 'Catering',
    section: 'Mid-page',
    description: 'Food set up for an event — trays of rice, meat, sauces laid out on a table. Guests or event context in background (blurred is fine).',
    dimensions: '700×480px',
    aspectRatio: '3:2',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'catering-event-setup.jpg',
  },

  // ─── ABOUT PAGE ──────────────────────────────────────────────────────────────
  {
    id: 'about-ibrahim',
    page: 'About',
    section: 'Story Section',
    description: 'Ibrahim cooking or plating — candid kitchen shot. At the grill, slicing meat, or laughing with a customer. Real, warm, not corporate.',
    dimensions: '700×480px',
    aspectRatio: '3:2',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'about-ibrahim-cooking.jpg',
  },
  {
    id: 'about-team',
    page: 'About',
    section: 'Meet the Family',
    description: 'Group photo of Ibrahim + Iman + Yasmin + Zainab together behind the counter or in the restaurant. Smiling, natural.',
    dimensions: '900×500px',
    aspectRatio: '9:5',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'about-team-group.jpg',
  },
  {
    id: 'about-iman',
    page: 'About',
    section: 'Team Cards',
    description: 'Iman at the counter or register — friendly, in action or smiling at camera',
    dimensions: '400×400px',
    aspectRatio: '1:1',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'about-iman.jpg',
  },
  {
    id: 'about-yasmin',
    page: 'About',
    section: 'Team Cards',
    description: 'Yasmin in the kitchen — plating or prepping, candid',
    dimensions: '400×400px',
    aspectRatio: '1:1',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'about-yasmin.jpg',
  },
  {
    id: 'about-zainab',
    page: 'About',
    section: 'Team Cards',
    description: 'Zainab at front of house — welcoming a customer or smiling at camera',
    dimensions: '400×400px',
    aspectRatio: '1:1',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'about-zainab.jpg',
  },

  // ─── MENU PAGE — APPETIZERS ──────────────────────────────────────────────────
  {
    id: 'menu-hummus',
    page: 'Menu',
    section: 'Appetizers',
    description: 'Hummus in a bowl — creamy, swirled top, olive oil pool, sprinkled paprika, served with pita triangles on the side',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'STOCK OK',
    canLaunchWithout: true,
    filename: 'menu-hummus.jpg',
  },
  {
    id: 'menu-hummus-lamb',
    page: 'Menu',
    section: 'Appetizers',
    description: 'Hummus with spiced ground lamb (hummus kawareh) — lamb piled in center of hummus bowl, pine nuts, olive oil drizzle',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-hummus-lamb.jpg',
  },
  {
    id: 'menu-tabouleh',
    page: 'Menu',
    section: 'Appetizers',
    description: 'Tabouleh salad — bright green parsley, diced red tomatoes, bulgur, lemon wedge. Vibrant overhead shot.',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'STOCK OK',
    canLaunchWithout: true,
    filename: 'menu-tabouleh.jpg',
  },
  {
    id: 'menu-house-salad',
    page: 'Menu',
    section: 'Appetizers',
    description: 'House salad — fresh chopped lettuce, tomato, cucumber, red onion in a bowl',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'NICE TO HAVE',
    photoType: 'STOCK OK',
    canLaunchWithout: true,
    filename: 'menu-house-salad.jpg',
  },
  {
    id: 'menu-falafel-app',
    page: 'Menu',
    section: 'Appetizers',
    description: 'Falafel (6 pcs) on a plate — golden brown, crispy, cracked open on one to show green inside. Tahini dipping sauce beside.',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-falafel-appetizer.jpg',
  },
  {
    id: 'menu-grape-leaves',
    page: 'Menu',
    section: 'Appetizers',
    description: 'Stuffed grape leaves arranged on a plate — rolled, tight, served with lemon wedge and yogurt dip',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'STOCK OK',
    canLaunchWithout: true,
    filename: 'menu-grape-leaves.jpg',
  },
  {
    id: 'menu-chicken-wings',
    page: 'Menu',
    section: 'Appetizers',
    description: 'Halal chicken wings — crispy, golden-brown, sauced or plain, piled on a plate with dipping sauce',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-chicken-wings.jpg',
  },
  {
    id: 'menu-mozz-sticks',
    page: 'Menu',
    section: 'Appetizers',
    description: 'Mozzarella sticks — golden fried, one broken open showing cheese pull, marinara sauce dip',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'NICE TO HAVE',
    photoType: 'STOCK OK',
    canLaunchWithout: true,
    filename: 'menu-mozzarella-sticks.jpg',
  },

  // ─── MENU PAGE — WRAPS ───────────────────────────────────────────────────────
  {
    id: 'menu-wrap-chicken-shawarma',
    page: 'Menu',
    section: 'Wraps',
    description: 'Chicken Shawarma Wrap — pita halved, chicken + veggies + garlic sauce visible inside. Shot from above or 45° on parchment.',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'menu-wrap-chicken-shawarma.jpg',
  },
  {
    id: 'menu-wrap-chicken-kabob',
    page: 'Menu',
    section: 'Wraps',
    description: 'Chicken Kabob Wrap — grilled chicken pieces in pita with vegetables, garlic sauce',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-wrap-chicken-kabob.jpg',
  },
  {
    id: 'menu-wrap-lamb-gyro',
    page: 'Menu',
    section: 'Wraps',
    description: 'Lamb Gyro Wrap — lamb slices in pita, tzatziki dripping, tomatoes and onions, cut in half revealing filling',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'menu-wrap-lamb-gyro.jpg',
  },
  {
    id: 'menu-wrap-combo-gyro',
    page: 'Menu',
    section: 'Wraps',
    description: 'Combo Gyro Wrap — chicken + lamb in pita, both sauces, fresh vegetables',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-wrap-combo-gyro.jpg',
  },
  {
    id: 'menu-wrap-falafel',
    page: 'Menu',
    section: 'Wraps',
    description: 'Falafel Wrap — falafel in pita, hummus smear, tomatoes, tahini drizzle. Vibrant vegetarian wrap.',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-wrap-falafel.jpg',
  },
  {
    id: 'menu-wrap-shish-tawook',
    page: 'Menu',
    section: 'Wraps',
    description: 'Shish Tawook Wrap — marinated grilled chicken cubes in pita, garlic mayo, tomatoes',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-wrap-shish-tawook.jpg',
  },
  {
    id: 'menu-wrap-kafta',
    page: 'Menu',
    section: 'Wraps',
    description: 'Kafta Wrap — spiced ground beef kafta in pita, grilled onions, tomatoes, tahini',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-wrap-kafta.jpg',
  },

  // ─── MENU PAGE — PLATTERS ────────────────────────────────────────────────────
  {
    id: 'menu-plat-chicken-rice',
    page: 'Menu',
    section: 'Platters',
    description: 'Chicken Over Rice — halal chicken slices on saffron rice, white + red sauce drizzled, side salad',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'menu-platter-chicken-over-rice.jpg',
  },
  {
    id: 'menu-plat-lamb-rice',
    page: 'Menu',
    section: 'Platters',
    description: 'Lamb Over Rice — halal lamb on saffron rice, sauces drizzled, generous portion',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'menu-platter-lamb-over-rice.jpg',
  },
  {
    id: 'menu-plat-combo-rice',
    page: 'Menu',
    section: 'Platters',
    description: 'Combo Over Rice — chicken + lamb on saffron rice, both sauces, side salad. THIS is the hero dish.',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'menu-platter-combo-over-rice.jpg',
  },
  {
    id: 'menu-plat-falafel-rice',
    page: 'Menu',
    section: 'Platters',
    description: 'Falafel Over Rice — crispy falafel on rice, tahini drizzle, colorful salad beside',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-platter-falafel-over-rice.jpg',
  },
  {
    id: 'menu-plat-shawarma-rice',
    page: 'Menu',
    section: 'Platters',
    description: 'Shawarma Over Rice — fresh-sliced chicken shawarma on saffron rice, sauces',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-platter-shawarma-over-rice.jpg',
  },

  // ─── MENU PAGE — GRILL ───────────────────────────────────────────────────────
  {
    id: 'menu-grill-mixed',
    page: 'Menu',
    section: 'Grill',
    description: 'Mixed Grill platter — lamb chops + chicken skewer + kafta on a large plate or over rice. Char marks, impressive portion.',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'menu-grill-mixed.jpg',
  },
  {
    id: 'menu-grill-lamb-chops',
    page: 'Menu',
    section: 'Grill',
    description: 'Lamb Chops — 2–3 chops on a plate, perfectly charred, herbs, lemon. Dramatic dark background.',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'menu-grill-lamb-chops.jpg',
  },
  {
    id: 'menu-grill-chicken-skewer',
    page: 'Menu',
    section: 'Grill',
    description: 'Chicken Skewer — juicy chicken pieces on metal skewer, char marks, served with rice or just the skewer',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-grill-chicken-skewer.jpg',
  },
  {
    id: 'menu-grill-kafta-skewer',
    page: 'Menu',
    section: 'Grill',
    description: 'Kafta Skewer — ground beef kafta on skewer, grilled, slight char, served on plate or over rice',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-grill-kafta-skewer.jpg',
  },
  {
    id: 'menu-grill-half-chicken',
    page: 'Menu',
    section: 'Grill',
    description: 'Half Chicken — whole half-chicken grilled, golden skin, served on plate. Impressive size.',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-grill-half-chicken.jpg',
  },

  // ─── MENU PAGE — FAMILY PLATTERS ─────────────────────────────────────────────
  {
    id: 'menu-fam-chicken',
    page: 'Menu',
    section: 'Family Platters',
    description: 'Family Chicken Platter — large foil tray or big dish of chicken over rice, enough for 3–4 people. Scale matters here.',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-family-chicken-platter.jpg',
  },
  {
    id: 'menu-fam-combo',
    page: 'Menu',
    section: 'Family Platters',
    description: 'Family Combo Platter — large shared tray of chicken + lamb over rice. Family gathered around it is a bonus.',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-family-combo-platter.jpg',
  },
  {
    id: 'menu-fam-mixed-grill',
    page: 'Menu',
    section: 'Family Platters',
    description: 'Family Mixed Grill — large spread: lamb chops, chicken, kafta all on one massive platter for sharing',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-family-mixed-grill.jpg',
  },

  // ─── MENU PAGE — DESSERTS ────────────────────────────────────────────────────
  {
    id: 'menu-baklava',
    page: 'Menu',
    section: 'Desserts',
    description: 'Baklava pieces — layers of phyllo, honey glistening on top, pistachio crumbles, golden-brown',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-dessert-baklava.jpg',
  },
  {
    id: 'menu-kunafa',
    page: 'Menu',
    section: 'Desserts',
    description: 'Kunafa — orange shredded pastry, cheese filling visible, sweet syrup drizzle, served warm',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'HIGH',
    photoType: 'REAL PHOTO',
    canLaunchWithout: true,
    filename: 'menu-dessert-kunafa.jpg',
  },
  {
    id: 'menu-rice-pudding',
    page: 'Menu',
    section: 'Desserts',
    description: 'Rice Pudding — creamy white pudding in a bowl, cinnamon sprinkled on top, raisins',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'NICE TO HAVE',
    photoType: 'STOCK OK',
    canLaunchWithout: true,
    filename: 'menu-dessert-rice-pudding.jpg',
  },

  // ─── MENU PAGE — DRINKS ──────────────────────────────────────────────────────
  {
    id: 'menu-tea',
    page: 'Menu',
    section: 'Drinks',
    description: 'Hot Black Tea — glass cup of dark tea, mint leaf floating, steam rising, dine-in table setting. THIS is one of the most-mentioned items in reviews. Must be a real photo.',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'MUST HAVE',
    photoType: 'REAL PHOTO',
    canLaunchWithout: false,
    filename: 'menu-drink-hot-black-tea.jpg',
  },
  {
    id: 'menu-soda',
    page: 'Menu',
    section: 'Drinks',
    description: 'Soft drinks — cans or cups of Coke/Sprite on a counter or table',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'NICE TO HAVE',
    photoType: 'STOCK OK',
    canLaunchWithout: true,
    filename: 'menu-drink-soda.jpg',
  },
  {
    id: 'menu-mango-juice',
    page: 'Menu',
    section: 'Drinks',
    description: 'Mango Juice — tall glass of bright orange-yellow mango juice, ice, maybe a mango slice garnish',
    dimensions: '500×375px',
    aspectRatio: '4:3',
    priority: 'NICE TO HAVE',
    photoType: 'STOCK OK',
    canLaunchWithout: true,
    filename: 'menu-drink-mango-juice.jpg',
  },

  // ─── TRUST BADGES / ICONS ────────────────────────────────────────────────────
  {
    id: 'badge-halal',
    page: 'All Pages',
    section: 'Trust Badges',
    description: '100% Halal Certified badge — circular seal design, green and gold, Arabic + English text. Custom designed graphic.',
    dimensions: '200×200px',
    aspectRatio: '1:1',
    priority: 'MUST HAVE',
    photoType: 'STOCK OK',
    canLaunchWithout: false,
    filename: 'badge-halal-certified.png',
  },
  {
    id: 'badge-open-late',
    page: 'Home',
    section: 'Trust Badges',
    description: 'Open Late icon — moon + clock graphic, dark/orange colors. Custom designed or SVG icon.',
    dimensions: '200×200px',
    aspectRatio: '1:1',
    priority: 'HIGH',
    photoType: 'STOCK OK',
    canLaunchWithout: true,
    filename: 'badge-open-late.png',
  },
  {
    id: 'badge-made-fresh',
    page: 'Home',
    section: 'Trust Badges',
    description: 'Made Fresh badge — leaf or flame icon, 